# Generated by Django 5.2 on 2025-05-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_investment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                (
                    "investment_type",
                    models.CharField(
                        choices=[
                            ("vesaf", "VESAF"),
                            ("vff", "VFF"),
                            ("vmeef", "VMEEF"),
                            ("veof", "VEOF"),
                            ("vibf", "VIBF"),
                            ("st", "stock"),
                            ("dcde", "DCDE"),
                            ("eth", "ETH"),
                            ("btc", "BTC"),
                        ],
                        max_length=15,
                    ),
                ),
                ("amount", models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
    ]
