# Generated by Django 5.2 on 2025-05-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_investment", "0002_investment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="investment_type",
            field=models.CharField(
                choices=[
                    ("VESAF", "VESAF"),
                    ("VFF", "VFF"),
                    ("VMEEF", "VMEEF"),
                    ("VEOF", "VEOF"),
                    ("VIBF", "VIBF"),
                    ("stock", "stock"),
                    ("DCDE", "DCDE"),
                    ("ETH", "ETH"),
                    ("BTC", "BTC"),
                ],
                max_length=15,
            ),
        ),
    ]
