# Generated by Django 5.2 on 2025-05-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackInvestment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("acbs", models.PositiveIntegerField(blank=True, default=0)),
                ("mio", models.PositiveIntegerField(blank=True, default=0)),
                ("dragon", models.PositiveIntegerField(blank=True, default=0)),
                ("ssi", models.PositiveIntegerField(blank=True, default=0)),
                ("idle_cash", models.PositiveIntegerField(blank=True, default=0)),
                ("crypto", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "total",
                    models.PositiveIntegerField(blank=True, default=0, editable=False),
                ),
            ],
        ),
    ]
