# Generated by Django 5.2.1 on 2025-05-12 04:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_investment", "0004_alter_investment_investment_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
