# Generated by Django 5.2.3 on 2025-06-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_investment", "0005_alter_investment_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dividend_new",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secCd", models.CharField(max_length=3)),
                (
                    "rightType",
                    models.CharField(
                        choices=[("cash", "cash"), ("stock", "stock")], max_length=5
                    ),
                ),
                ("ownQty", models.PositiveSmallIntegerField()),
                ("recAmt", models.PositiveIntegerField()),
                ("recQty", models.PositiveSmallIntegerField()),
                ("ownerFixDate", models.DateField()),
                ("expectedExcDate", models.DateField()),
            ],
        ),
    ]
