# Generated by Django 5.2.1 on 2025-05-19 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_investment", "0005_alter_investment_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dividend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("secCd", models.CharField(max_length=10)),
                (
                    "rightType",
                    models.CharField(
                        choices=[("stock", "stock"), ("cash", "cash")], max_length=10
                    ),
                ),
                ("ownQty", models.PositiveIntegerField(default=0)),
                ("amount", models.PositiveIntegerField(blank=True, default=0)),
                ("ownerFixDate", models.DateField(blank=True, null=True)),
                ("expectedExcDate", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
