# Session settings
SESSION_EXPIRE_SECONDS = 3600*8  # 1 hour
SESSION_EXPIRE_AFTER_LAST_ACTIVITY_GRACE_PERIOD = 3600  # group by minute
SESSION_EXPIRE_AFTER_LAST_ACTIVITY = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_TIMEOUT_REDIRECT = '/'