# Generated by Django 5.2.1 on 2025-05-15 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackGym",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        blank=True,
                        choices=[("Phat", "Phat")],
                        default="Phat",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("date", models.DateField()),
                ("start", models.DateTimeField(default=django.utils.timezone.now)),
                ("end", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "routine",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Pushday", "Pushday"),
                            ("Pullday", "Pullday"),
                            ("Legday", "Legday"),
                            ("Absday", "Absday"),
                            ("Cardio", "Cardio"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
            ("duration", models.CharField(default="0", editable=False)),
            ],
        ),
    ]
