# Generated by Django 5.2.1 on 2025-05-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_fitness", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymtrack",
            name="duration",
            field=models.DurationField(default=0, editable=False),
        ),
    ]
