# Generated by Django 5.2.1 on 2025-05-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_fitness", "0002_gymtrack_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymtrack",
            name="duration",
            field=models.CharField(default="0", editable=False),
        ),
    ]
