# Generated by Django 5.2 on 2025-05-05 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("user", models.CharField(choices=[("ph", "Phat")], max_length=50)),
                ("cash", models.PositiveIntegerField(blank=True)),
                ("digital", models.PositiveIntegerField(blank=True)),
                ("credit", models.PositiveIntegerField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FD", "Food & drinks"),
                            ("G", "Gas"),
                            ("Gr", "Grocery"),
                            ("Md", "Medical"),
                            ("Sc", "Subscription"),
                            ("Ut", "Utility"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(max_length=200)),
            ],
        ),
    ]
