# Generated by Django 5.2.1 on 2025-05-12 04:28

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("phat_investment", "0004_alter_investment_investment_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=20)),
                ("bought_price", models.PositiveIntegerField(blank=True, default=0)),
                ("amount", models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Conversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                (
                    "type_conversion",
                    models.CharField(
                        choices=[
                            ("digital_cash", "digital_cash"),
                            ("cash_digital", "cash_digital"),
                        ],
                        default="digital_cash",
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                ("conversion_amount", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Debts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(auto_now=True)),
                (
                    "due_date",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime(
                            2025, 5, 12, 4, 28, 16, 826103, tzinfo=datetime.timezone.utc
                        ),
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("debt", "debt"), ("lend", "lend")], default="lend"
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                ("client", models.CharField(blank=True, max_length=30)),
                ("total", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("deposite", "deposite"), ("withdraw", "withdraw")],
                        default="deposite",
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=datetime.date.today)),
                (
                    "user",
                    models.CharField(
                        blank=True,
                        choices=[("Phat", "Phat")],
                        default="Phat",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("cash", models.PositiveIntegerField(blank=True, default=0)),
                ("digital", models.PositiveIntegerField(blank=True, default=0)),
                ("credit", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food&drinks", "food&drinks"),
                            ("gas", "gas"),
                            ("dating", "dating"),
                            ("grocery", "grocery"),
                            ("medical", "medical"),
                            ("subscriptions", "subscriptions"),
                            ("utility", "utility"),
                            ("others", "others"),
                            ("pleasure", "pleasure"),
                            ("inbody", "inbody"),
                            ("bikecare", "bikecare"),
                            ("insurance", "insurance"),
                            ("gift", "gift"),
                            ("donation", "donation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InOutFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SinkingFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("deposite", "deposite"), ("withdraw", "withdraw")],
                        default="deposite",
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_month",
                    models.DateField(auto_now=True, verbose_name="Month/Year"),
                ),
                ("expense", models.PositiveIntegerField(default=0)),
                ("cash", models.PositiveIntegerField(default=0)),
                ("digital", models.PositiveIntegerField(default=0)),
                ("networth", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phat_finance.assets",
                    ),
                ),
                (
                    "investment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phat_investment.investment",
                    ),
                ),
                (
                    "debt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phat_finance.debts",
                    ),
                ),
                (
                    "emergency_fund",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phat_finance.emergencyfund",
                    ),
                ),
                (
                    "sink_fund",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phat_finance.sinkingfund",
                    ),
                ),
            ],
        ),
    ]
