# Generated by Django 5.2 on 2025-05-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="cash",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="credit",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="digital",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
