# Generated by Django 5.2 on 2025-05-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0002_alter_expenses_cash_alter_expenses_credit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="user",
            field=models.CharField(
                choices=[("ph", "Phat")], default="ph", max_length=50
            ),
        ),
    ]
