# Generated by Django 5.2 on 2025-05-09 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0002_alter_debts_due_date_alter_expenses_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debts",
            name="due_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 5, 9, 16, 13, 35, 464468, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
