# Generated by Django 5.2.1 on 2025-05-22 23:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0002_alter_debts_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="inoutflow",
            name="_type",
            field=models.CharField(
                choices=[("IN", "IN"), ("OUT", "OUT")], default="IN", max_length=5
            ),
        ),
        migrations.AddField(
            model_name="inoutflow",
            name="amount",
            field=models.PositiveIntegerField(blank=True, default=0, editable=False),
        ),
        migrations.AddField(
            model_name="inoutflow",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name="inoutflow",
            name="placeholder",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="balance",
            name="asset",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="balance",
            name="debt",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="balance",
            name="emergency_fund",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="balance",
            name="investment",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="balance",
            name="sink_fund",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
