# Generated by Django 5.2 on 2025-05-09 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0003_alter_debts_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="balance",
            name="expense",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="debts",
            name="due_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 5, 9, 16, 39, 46, 587146, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.DeleteModel(
            name="TotalExpenses",
        ),
    ]
