# Generated by Django 5.2 on 2025-05-06 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0003_alter_expenses_user"),
        ("phat_investment", "0002_investment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Conversion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now=True)),
                (
                    "type_conversion",
                    models.CharField(
                        choices=[
                            ("digital_cash", "digital_cash"),
                            ("cash_digital", "cash_digital"),
                        ],
                        default="digital_cash",
                    ),
                ),
                ("amount", models.PositiveIntegerField(default=0)),
                ("conversion_amount", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Debts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InOutFlow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SinkingFund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TotalExpenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_month",
                    models.DateField(auto_now=True, verbose_name="Month/Year"),
                ),
                ("total_cash", models.PositiveIntegerField(blank=True, default=0)),
                ("total_digital", models.PositiveIntegerField(blank=True, default=0)),
                ("total_credit", models.PositiveIntegerField(blank=True, default=0)),
                ("total_expense", models.PositiveIntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_month",
                    models.DateField(auto_now=True, verbose_name="Month/Year"),
                ),
                ("cash", models.PositiveIntegerField(default=0)),
                ("digital", models.PositiveIntegerField(default=0)),
                ("networth", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phat_finance.assets",
                    ),
                ),
                (
                    "investment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phat_investment.investment",
                    ),
                ),
                (
                    "debt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phat_finance.debts",
                    ),
                ),
                (
                    "emergency_fund",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phat_finance.emergencyfund",
                    ),
                ),
                (
                    "sink_fund",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phat_finance.sinkingfund",
                    ),
                ),
                (
                    "expense",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="phat_finance.totalexpenses",
                    ),
                ),
            ],
        ),
    ]
