# Generated by Django 5.2.1 on 2025-05-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0003_rename_expenses_expense_inoutflow__type_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="inoutflow",
            old_name="_type",
            new_name="type",
        ),
    ]
