# Generated by Django 5.2.1 on 2025-05-28 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0004_rename__type_inoutflow_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inoutflow",
            name="placeholder",
        ),
        migrations.AlterField(
            model_name="inoutflow",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="inoutflow",
            name="type",
            field=models.CharField(
                choices=[("IN", "IN"), ("OUT", "OUT"), ("SALARY", "SALARY")],
                default="IN",
                max_length=10,
            ),
        ),
    ]
