# Generated by Django 5.2 on 2025-05-06 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "phat_finance",
            "0004_assets_conversion_debts_emergencyfund_inoutflow_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assets",
            name="amount",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="assets",
            name="bought_price",
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name="assets",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="assets",
            name="name",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="debts",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="debts",
            name="client",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="debts",
            name="due_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 5, 6, 8, 47, 36, 608932, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AddField(
            model_name="debts",
            name="start_date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="debts",
            name="total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="debts",
            name="type",
            field=models.CharField(
                choices=[("debt", "debt"), ("lend", "lend")], default="lend"
            ),
        ),
        migrations.AddField(
            model_name="emergencyfund",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="emergencyfund",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="emergencyfund",
            name="type",
            field=models.CharField(
                choices=[("deposite", "deposite"), ("withdraw", "withdraw")],
                default="deposite",
            ),
        ),
        migrations.AddField(
            model_name="sinkingfund",
            name="amount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sinkingfund",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="sinkingfund",
            name="type",
            field=models.CharField(
                choices=[("deposite", "deposite"), ("withdraw", "withdraw")],
                default="deposite",
            ),
        ),
    ]
