# Generated by Django 5.2 on 2025-05-06 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0005_assets_amount_assets_bought_price_assets_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debts",
            name="due_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 5, 6, 9, 10, 49, 681014, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
