# Generated by Django 5.2.1 on 2025-05-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "phat_finance",
            "0005_remove_inoutflow_placeholder_alter_inoutflow_amount_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conversion",
            name="conversion_amount",
        ),
    ]
