# Generated by Django 5.2.1 on 2025-05-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0006_remove_conversion_conversion_amount"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Balance",
        ),
        migrations.AlterField(
            model_name="conversion",
            name="type_conversion",
            field=models.CharField(
                choices=[
                    ("digital📲_cash💵", "digital📲_cash💵"),
                    ("cash💵_digital📲", "cash💵_digital📲"),
                ],
                default="digital_cash",
            ),
        ),
        migrations.AlterField(
            model_name="inoutflow",
            name="type",
            field=models.CharField(
                choices=[("IN", "IN"), ("OUT", "OUT"), ("SALARY 💵💻", "SALARY 💵💻")],
                default="IN",
                max_length=10,
            ),
        ),
    ]
