# Generated by Django 5.2 on 2025-05-06 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0006_alter_debts_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assets",
            name="amount",
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name="debts",
            name="due_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 5, 6, 9, 17, 10, 478534, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
