# Generated by Django 5.2 on 2025-05-06 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0007_alter_assets_amount_alter_debts_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debts",
            name="due_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 5, 6, 9, 26, 10, 364450, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
    ]
