# Generated by Django 5.2.1 on 2025-05-29 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "phat_finance",
            "0007_delete_balance_alter_conversion_type_conversion_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="assets",
            old_name="bought_price",
            new_name="price",
        ),
        migrations.AddField(
            model_name="assets",
            name="transac_type",
            field=models.CharField(
                blank=True, choices=[("buy", "buy"), ("sell", "sell")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="emergencyfund",
            name="date",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
