# Generated by Django 5.2 on 2025-05-07 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0008_alter_debts_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debts",
            name="due_date",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(
                    2025, 5, 7, 17, 55, 8, 885427, tzinfo=datetime.timezone.utc
                ),
            ),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="category",
            field=models.CharField(
                choices=[
                    ("food & drinks", "food & drinks"),
                    ("gas", "Gas"),
                    ("grocery", "grocery"),
                    ("medical", "medical"),
                    ("subscription", "subscription"),
                    ("utility", "utility"),
                    ("others", "others"),
                    ("pleasure", "pleasure"),
                    ("inbody", "inbody"),
                    ("bikecare", "bikecare"),
                    ("insurance", "insurance"),
                    ("gift", "gift"),
                    ("donation", "donation"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="user",
            field=models.CharField(
                blank=True,
                choices=[("Phat", "Phat")],
                default="Phat",
                max_length=50,
                null=True,
            ),
        ),
    ]
