# Generated by Django 5.2.2 on 2025-06-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "phat_finance",
            "0009_rename_client_debts_borrower_remove_debts_total_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("food&drinks", "food&drinks"),
                    ("gas", "gas"),
                    ("dating", "dating"),
                    ("grocery", "grocery"),
                    ("medical", "medical"),
                    ("subscriptions", "subscriptions"),
                    ("utility", "utility"),
                    ("others", "others"),
                    ("pleasure", "pleasure"),
                    ("inbody", "inbody"),
                    ("bikecare", "bikecare"),
                    ("insurance", "insurance"),
                    ("gift", "gift"),
                    ("donation", "donation"),
                    ("haircut", "haircut"),
                ],
                max_length=50,
            ),
        ),
    ]
