# Generated by Django 5.2.4 on 2025-07-26 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0010_alter_expense_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditCardPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.DateField(default=datetime.date.today)),
                ("amount", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("food_drink 🍔🍜☕", "food_drink 🍔🍜☕"),
                    ("gas ⛽⚡🚛", "gas ⛽⚡🚛"),
                    ("dating 😘😻💌", "dating 😘😻💌"),
                    ("grocery 🛒🥦🥩", "grocery 🛒🥦🥩"),
                    ("medical 💊🧑\u200d⚕️🩺", "medical 💊🧑\u200d⚕️🩺"),
                    ("subscriptions💳💸🏦", "subscriptions💳💸🏦"),
                    ("utility ⚙️🪒🪠", "utility ⚙️🪒🪠"),
                    ("others🙄😏", "others🙄😏"),
                    ("pleasure🥳🎉🪩", "pleasure🥳🎉🪩"),
                    ("bikecare 🏍️🛣️🧑\u200d🔧", "bikecare 🏍️🛣️🧑\u200d🔧"),
                    ("insurance", "insurance"),
                    ("gifts🎁💌💐", "gifts🎁💌💐"),
                    ("donation 🧧💸🫂", "donation 🧧💸🫂"),
                    ("haircut 💇\u200d♂️💈👱", "haircut 💇\u200d♂️💈👱"),
                ],
                max_length=50,
            ),
        ),
    ]
