# Generated by Django 5.2.4 on 2025-07-26 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0011_creditcardpayment_alter_expense_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcardpayment",
            name="term",
            field=models.CharField(max_length=7),
        ),
    ]
