# Generated by Django 5.2.4 on 2025-07-26 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phat_finance", "0012_alter_creditcardpayment_term"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcardpayment",
            name="card",
            field=models.CharField(
                choices=[("VISA Platinum", "VISA Platinum"), ("VJB", "VJB")],
                default="VISA Platinum",
                max_length=20,
            ),
        ),
    ]
